version: "3.8"

services:
  postgres:
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 10
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - 5434:5432

  backend:
    restart: on-failure
    build:
      context: ./backend
      dockerfile: Dockerfile

    ports:
      - 3000:3000

    depends_on:
      postgres:
        condition: service_healthy

    environment:
      DATABASE_URL: ${DATABASE_URL}

    volumes:
      - ./images:/app/images
  
  fronted:
    restart: on-failure
    build:
      context: ./frontend
      dockerfile: Dockerfile

    ports:
      - 4000:3000
  
  admin:
    restart: on-failure
    build:
      context: ./admin
      dockerfile: Dockerfile

    ports:
      - 4001:3000


  
